services:
  node:
    build: ./
    user: root
    volumes:
      - ./:/usr/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: ['npm', 'run', 'start:dev']
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    ports:
      - ${DATABASE_EXTERNAL_PORT}:5432